In [1]:
#Jesse McGough
#100558261

import numpy as np

#Compares the given colour map with the colour white (which is [1,1,1])
def WhiteWash(colourmap):
    for i in range(len(colourmap)):
        colourmap[i][0] = (colourmap[i][0]+1)/2
        colourmap[i][1] = (colourmap[i][1]+1)/2
        colourmap[i][2] = (colourmap[i][2]+1)/2
    return colourmap

#Creates a random colour map for input
colours = np.random.rand(4,3)

#Prints out what is needed
print("Map before WhiteWash:")
print(colours)
print("Map after WhiteWash:")
print(WhiteWash(colours))

Map before WhiteWash:
[[ 0.35111232  0.7128979   0.28672062]
 [ 0.12826558  0.77797793  0.2453704 ]
 [ 0.15861325  0.77122589  0.01529848]
 [ 0.23558588  0.54175746  0.06762492]]
Map after WhiteWash:
[[ 0.67555616  0.85644895  0.64336031]
 [ 0.56413279  0.88898896  0.6226852 ]
 [ 0.57930663  0.88561294  0.50764924]
 [ 0.61779294  0.77087873  0.53381246]]
